from enum import Enum

class GammaRegime(Enum):
    LONG_GAMMA = "LONG_GAMMA"
    SHORT_GAMMA = "SHORT_GAMMA"
    TRANSITION_REGIME = "TRANSITION_REGIME"

class SetupType(Enum):
    GAMMA_SQUEEZE = "GAMMA_SQUEEZE"
    VOLATILITY_COIL = "VOLATILITY_COIL"
    FLOOR_BOUNCE = "FLOOR_BOUNCE"
    DEALER_DEFENSE = "DEALER_DEFENSE"
    REGIME_SHIFT = "REGIME_SHIFT"
    INVENTORY_MIGRATION = "INVENTORY_MIGRATION"

# String Constants for Backwards Compatibility
SETUP_GAMMA_SQUEEZE = SetupType.GAMMA_SQUEEZE.value
SETUP_VOLATILITY_COIL = SetupType.VOLATILITY_COIL.value
SETUP_FLOOR_BOUNCE = SetupType.FLOOR_BOUNCE.value
SETUP_DEALER_DEFENSE = SetupType.DEALER_DEFENSE.value
SETUP_REGIME_SHIFT = SetupType.REGIME_SHIFT.value
SETUP_INVENTORY_MIGRATION = SetupType.INVENTORY_MIGRATION.value

REGIME_LONG_GAMMA = GammaRegime.LONG_GAMMA.value
REGIME_SHORT_GAMMA = GammaRegime.SHORT_GAMMA.value
REGIME_TRANSITION = GammaRegime.TRANSITION_REGIME.value
