# F&O Universe Sector/Industry Mapping Catalog
# Authoritative sector classification mapping for active F&O tickers

SECTOR_MAPPING = {
    # ── INDICES ──
    "NIFTY": "Index",
    "BANKNIFTY": "Index",
    "FINNIFTY": "Index",
    "MIDCPNIFTY": "Index",
    "NIFTYNXT50": "Index",

    # ── BFSI (Banking, Financial Services & Insurance) ──
    "HDFCBANK": "BFSI",
    "ICICIBANK": "BFSI",
    "AXISBANK": "BFSI",
    "SBIN": "BFSI",
    "KOTAKBANK": "BFSI",
    "PNB": "BFSI",
    "BANKBARODA": "BFSI",
    "FEDERALBNK": "BFSI",
    "YESBANK": "BFSI",
    "BANDHANBNK": "BFSI",
    "IDFCFIRSTB": "BFSI",
    "UNIONBANK": "BFSI",
    "CANBK": "BFSI",
    "BANKINDIA": "BFSI",
    "INDIANB": "BFSI",
    "RBLBANK": "BFSI",
    "CHOLAFIN": "BFSI",
    "RECLTD": "BFSI",
    "PFC": "BFSI",
    "SHRIRAMFIN": "BFSI",
    "MUTHOOTFIN": "BFSI",
    "LICHSGFIN": "BFSI",
    "LICI": "BFSI",
    "SBICARD": "BFSI",
    "SBILIFE": "BFSI",
    "ICICIGI": "BFSI",
    "ICICIPRULI": "BFSI",
    "HDFCLIFE": "BFSI",
    "MFSL": "BFSI",
    "HDFCAMC": "BFSI",
    "CAMS": "BFSI",
    "BSE": "BFSI",
    "CDSL": "BFSI",
    "MCX": "BFSI",
    "NUVAMA": "BFSI",
    "ANGELONE": "BFSI",
    "KFINTECH": "BFSI",
    "MOTILALOFS": "BFSI",
    "360ONE": "BFSI",
    "SAMMAANCAP": "BFSI",

    # ── IT & TELECOM ──
    "TCS": "IT & Telecom",
    "INFY": "IT & Telecom",
    "WIPRO": "IT & Telecom",
    "HCLTECH": "IT & Telecom",
    "TECHM": "IT & Telecom",
    "LTM": "IT & Telecom",
    "PERSISTENT": "IT & Telecom",
    "COFORGE": "IT & Telecom",
    "OFSS": "IT & Telecom",
    "MPHASIS": "IT & Telecom",
    "TATAELXSI": "IT & Telecom",
    "KPITTECH": "IT & Telecom",
    "NAUKRI": "IT & Telecom",
    "BHARTIARTL": "IT & Telecom",
    "INDUSTOWER": "IT & Telecom",
    "IDEA": "IT & Telecom",

    # ── ENERGY, POWER & UTILITIES ──
    "RELIANCE": "Energy & Power",
    "ONGC": "Energy & Power",
    "OIL": "Energy & Power",
    "BPCL": "Energy & Power",
    "IOC": "Energy & Power",
    "HINDPETRO": "Energy & Power",
    "COALINDIA": "Energy & Power",
    "NTPC": "Energy & Power",
    "POWERGRID": "Energy & Power",
    "TATAPOWER": "Energy & Power",
    "NHPC": "Energy & Power",
    "JSWENERGY": "Energy & Power",
    "ADANIENSOL": "Energy & Power",
    "ADANIPOWER": "Energy & Power",
    "ADANIGREEN": "Energy & Power",
    "IREDA": "Energy & Power",
    "SUZLON": "Energy & Power",
    "INOXWIND": "Energy & Power",
    "WAAREEENER": "Energy & Power",
    "PREMIERENE": "Energy & Power",
    "RVNL": "Energy & Power",
    "IRFC": "Energy & Power",

    # ── CAPITAL GOODS & INFRASTRUCTURE ──
    "LT": "Capital Goods & Infra",
    "BEL": "Capital Goods & Infra",
    "HAL": "Capital Goods & Infra",
    "BDL": "Capital Goods & Infra",
    "CUMMINSIND": "Capital Goods & Infra",
    "SIEMENS": "Capital Goods & Infra",
    "ABB": "Capital Goods & Infra",
    "BHEL": "Capital Goods & Infra",
    "CGPOWER": "Capital Goods & Infra",
    "GVT&D": "Capital Goods & Infra",
    "POWERINDIA": "Capital Goods & Infra",
    "MAZDOCK": "Capital Goods & Infra",
    "COCHINSHIP": "Capital Goods & Infra",
    "SOLARINDS": "Capital Goods & Infra",
    "BHARATFORG": "Capital Goods & Infra",

    # ── AUTOMOBILE & AUTO ANCILLARIES ──
    "MARUTI": "Automobile",
    "M&M": "Automobile",
    "HEROMOTOCO": "Automobile",
    "BAJAJ-AUTO": "Automobile",
    "TVSMOTOR": "Automobile",
    "ASHOKLEY": "Automobile",
    "EICHERMOT": "Automobile",
    "BOSCHLTD": "Automobile",
    "MOTHERSON": "Automobile",
    "UNOMINDA": "Automobile",
    "SONACOMS": "Automobile",
    "EXIDEIND": "Automobile",
    "TIINDIA": "Automobile",
    "TMPV": "Automobile",

    # ── PHARMACEUTICALS & HEALTHCARE ──
    "SUNPHARMA": "Healthcare & Pharma",
    "CIPLA": "Healthcare & Pharma",
    "DRREDDY": "Healthcare & Pharma",
    "APOLLOHOSP": "Healthcare & Pharma",
    "DIVISLAB": "Healthcare & Pharma",
    "AUROPHARMA": "Healthcare & Pharma",
    "LUPIN": "Healthcare & Pharma",
    "ZYDUSLIFE": "Healthcare & Pharma",
    "MANKIND": "Healthcare & Pharma",
    "ALKEM": "Healthcare & Pharma",
    "GLENMARK": "Healthcare & Pharma",
    "LAURUSLABS": "Healthcare & Pharma",
    "FORTIS": "Healthcare & Pharma",
    "MAXHEALTH": "Healthcare & Pharma",
    "BIOCON": "Healthcare & Pharma",
    "TORNTPHARM": "Healthcare & Pharma",

    # ── FMCG & CONSUMER DISCRETIONARY ──
    "HINDUNILVR": "FMCG & Consumer Goods",
    "ITC": "FMCG & Consumer Goods",
    "NESTLEIND": "FMCG & Consumer Goods",
    "BRITANNIA": "FMCG & Consumer Goods",
    "COLPAL": "FMCG & Consumer Goods",
    "DABUR": "FMCG & Consumer Goods",
    "MARICO": "FMCG & Consumer Goods",
    "PATANJALI": "FMCG & Consumer Goods",
    "VBL": "FMCG & Consumer Goods",
    "PAGEIND": "FMCG & Consumer Goods",
    "JUBLFOOD": "FMCG & Consumer Goods",
    "TRENT": "FMCG & Consumer Goods",
    "TITAN": "FMCG & Consumer Goods",
    "KALYANKJIL": "FMCG & Consumer Goods",
    "NYKAA": "FMCG & Consumer Goods",
    "SWIGGY": "FMCG & Consumer Goods",
    "RADICO": "FMCG & Consumer Goods",
    "UNITDSPR": "FMCG & Consumer Goods",

    # ── METALS & MINING ──
    "TATASTEEL": "Metals & Mining",
    "JSWSTEEL": "Metals & Mining",
    "HINDALCO": "Metals & Mining",
    "VEDL": "Metals & Mining",
    "NATIONALUM": "Metals & Mining",
    "NMDC": "Metals & Mining",
    "HINDZINC": "Metals & Mining",
    "JINDALSTEL": "Metals & Mining",
    "SAIL": "Metals & Mining",

    # ── CHEMICALS & AGROCHEMICALS ──
    "PIDILITIND": "Chemicals",
    "SRF": "Chemicals",
    "UPL": "Chemicals",
    "PIIND": "Chemicals",

    # ── REAL ESTATE, CEMENT & BUILDING MATERIALS ──
    "DLF": "Real Estate & Cement",
    "LODHA": "Real Estate & Cement",
    "OBEROIRLTY": "Real Estate & Cement",
    "PRESTIGE": "Real Estate & Cement",
    "PHOENIXLTD": "Real Estate & Cement",
    "ASTRAL": "Real Estate & Cement",
    "SUPREMEIND": "Real Estate & Cement",
    "VOLTAS": "Real Estate & Cement",
    "HAVELLS": "Real Estate & Cement",
    "CROMPTON": "Real Estate & Cement",
    "DIXON": "Real Estate & Cement",
    "AMBER": "Real Estate & Cement",
    "NBCC": "Real Estate & Cement",
    "PGEL": "Real Estate & Cement",
    "ULTRACEMCO": "Real Estate & Cement",
    "AMBUJACEM": "Real Estate & Cement",
    "SHREECEM": "Real Estate & Cement",
    "DALBHARAT": "Real Estate & Cement",

    # ── TRANSPORTATION & LOGISTICS ──
    "ADANIPORTS": "Logistics & Transport",
    "INDIGO": "Logistics & Transport",
    "CONCOR": "Logistics & Transport",
    "DELHIVERY": "Logistics & Transport",

    # ── ADANI GROUP CONGLOMERATE (MULTI-SECTOR EX-POWER/PORTS) ──
    "ADANIENT": "Diversified",
    "ADANIPOWER": "Energy & Power",
    "ADANIGREEN": "Energy & Power",
    "ADANIPORTS": "Logistics & Transport",
    "ADANIENSOL": "Energy & Power"
}

def get_sector(symbol: str) -> str:
    """Helper function to resolve the sector of a symbol, defaulting to 'Other' if unmapped."""
    return SECTOR_MAPPING.get(symbol, "Other")
